import { useState, useEffect } from 'react';
import Header from './components/Header';
import Footer from './components/Footer';
import HomeView from './components/HomeView';
import BlogView from './components/BlogView';
import ReviewsView from './components/ReviewsView';
import AboutView from './components/AboutView';
import ContactView from './components/ContactView';
import AIWizard from './components/AIWizard';
import TelemetryHub from './components/TelemetryHub';
import ReaderView from './components/ReaderView';
import { MOCK_POSTS, MOCK_ADS } from './mockData';
import { Post } from './types';

export default function App() {
  const [currentTab, setCurrentTab] = useState<string>('home');
  const [activeArticleId, setActiveArticleId] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [darkTheme, setDarkTheme] = useState<boolean>(true);
  
  // Local posts array (including mock posts + any generated by Gemini)
  const [posts, setPosts] = useState<Post[]>(MOCK_POSTS);
  
  // Telemetry metric state fetched from API
  const [telemetry, setTelemetry] = useState({
    totalClicks: 462,
    totalSales: 30,
    totalCommission: 663.50,
    subscribersCount: 28,
    activeReadersToday: 4296,
    affiliateStats: [
      { serviceId: 'rank-in-chatgpt', serviceName: 'ChatGPT SEO Masterclass Course', clicks: 231, salesSimulated: 18, commissionEarned: 427.5 },
      { serviceId: 'review-rankforge-ai', serviceName: 'RankForge AI Subscription', clicks: 142, salesSimulated: 8, commissionEarned: 196.0 },
      { serviceId: 'alternative-credits', serviceName: 'Partner Tech Alternative Listings', clicks: 89, salesSimulated: 4, commissionEarned: 40.0 }
    ]
  });

  // Track liked articles locally
  const [likedPosts, setLikedPosts] = useState<string[]>([]);

  // Fetch telemetry from full-stack server
  const fetchTelemetry = async () => {
    try {
      const res = await fetch('/api/telemetry/stats');
      if (res.ok) {
        const data = await res.json();
        setTelemetry(data);
      }
    } catch (err) {
      console.warn("Telemetry API offline. Running local browser simulation:", err);
    }
  };

  useEffect(() => {
    fetchTelemetry();
    // Refresh stats every 15 seconds to simulate real organic background scraper clicks
    const interval = setInterval(() => {
      fetchTelemetry();
    }, 15000);
    return () => clearInterval(interval);
  }, []);

  // Update theme class on HTML element
  useEffect(() => {
    const root = window.document.documentElement;
    if (darkTheme) {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
  }, [darkTheme]);

  // Handle click on affiliate link
  const handleIncrementClicks = async (serviceId: string) => {
    try {
      const res = await fetch('/api/telemetry/click', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ serviceId })
      });
      if (res.ok) {
        // Fetch updated logs
        fetchTelemetry();
      } else {
        throw new Error("Server reporting error");
      }
    } catch (err) {
      // Local fallback simulation if server is still starting or compiling
      setTelemetry((prev: any) => {
        const stats = [...prev.affiliateStats];
        let matched = stats.find(s => s.serviceId === serviceId);
        if (!matched) {
          matched = { serviceId, serviceName: serviceId, clicks: 0, salesSimulated: 0, commissionEarned: 0 };
          stats.push(matched);
        }
        matched.clicks += 1;
        
        // 10% chance of local sales generation
        if (Math.random() < 0.1) {
          matched.salesSimulated += 1;
          matched.commissionEarned += serviceId.includes('chatgpt') ? 35.00 : 24.50;
        }

        const sumClicks = stats.reduce((sum, item) => sum + item.clicks, 0);
        const sumSales = stats.reduce((sum, item) => sum + item.salesSimulated, 0);
        const sumCommission = stats.reduce((sum, item) => sum + item.commissionEarned, 0);

        return {
          ...prev,
          affiliateStats: stats,
          totalClicks: sumClicks,
          totalSales: sumSales,
          totalCommission: sumCommission
        };
      });
    }
  };

  // Subscribe to newsletter trigger
  const handleSubscribeNewsletter = async (email: string) => {
    try {
      const res = await fetch('/api/newsletter/subscribe', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, categories: ['ai-news', 'tech-news', 'reviews'] })
      });
      const data = await res.json();
      fetchTelemetry();
      return { success: true, message: data.message || "Subscribed successfully!" };
    } catch (err) {
      // Fallback local simulation
      setTelemetry(prev => ({
        ...prev,
        subscribersCount: prev.subscribersCount + 1
      }));
      return {
        success: true,
        message: "Simulated Subscription Success! Registered under Farma Digital Reports."
      };
    }
  };

  // Reset metrics
  const handleResetTelemetryMetric = () => {
    setTelemetry({
      totalClicks: 0,
      totalSales: 0,
      totalCommission: 0.00,
      subscribersCount: 1,
      activeReadersToday: 4252,
      affiliateStats: [
        { serviceId: 'rank-in-chatgpt', serviceName: 'ChatGPT SEO Masterclass Course', clicks: 0, salesSimulated: 0, commissionEarned: 0 },
        { serviceId: 'review-rankforge-ai', serviceName: 'RankForge AI Subscription', clicks: 0, salesSimulated: 0, commissionEarned: 0 },
        { serviceId: 'alternative-credits', serviceName: 'Partner Tech Alternative Listings', clicks: 0, salesSimulated: 0, commissionEarned: 0 }
      ]
    });
  };

  const handleAddCustomPost = (newPost: Post) => {
    setPosts(prev => [newPost, ...prev]);
    // Navigate directly to blog and set the active view to read the newly generated post!
    setActiveArticleId(newPost.id);
  };

  const handleLikePost = (id: string) => {
    if (likedPosts.includes(id)) {
      setLikedPosts(prev => prev.filter(pId => pId !== id));
    } else {
      setLikedPosts(prev => [...prev, id]);
    }
  };

  const handleReadArticle = (id: string) => {
    setActiveArticleId(id);
    // Track auto click view counts
    setPosts(prev => prev.map(p => p.id === id ? { ...p, views: p.views + 1 } : p));
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const activePost = posts.find(p => p.id === activeArticleId);

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950 text-gray-900 dark:text-gray-100 flex flex-col justify-between font-sans transition-colors duration-200">
      
      {/* 1. Header Integration */}
      <Header
        currentTab={currentTab}
        setCurrentTab={(tab) => {
          setCurrentTab(tab);
          setActiveArticleId(null);
          window.scrollTo({ top: 0, behavior: 'smooth' });
        }}
        darkTheme={darkTheme}
        setDarkTheme={setDarkTheme}
        searchQuery={searchQuery}
        setSearchQuery={(q) => {
          setSearchQuery(q);
          if (currentTab !== 'blog') setCurrentTab('blog');
          setActiveArticleId(null);
        }}
        subscriberCount={telemetry.subscribersCount}
        totalEarnings={telemetry.totalCommission}
      />

      {/* 2. Main Platform Screen routing controller */}
      <main className="flex-1">
        {activeArticleId && activePost ? (
          <ReaderView
            post={activePost}
            onBack={() => setActiveArticleId(null)}
            onIncrementClicks={handleIncrementClicks}
            onLikePost={handleLikePost}
            likedPosts={likedPosts}
          />
        ) : (
          <>
            {currentTab === 'home' && (
              <HomeView
                posts={posts}
                ads={MOCK_ADS}
                onReadArticle={handleReadArticle}
                onNavigateTab={(tab) => {
                  setCurrentTab(tab);
                  window.scrollTo({ top: 0, behavior: 'smooth' });
                }}
                onIncrementClicks={handleIncrementClicks}
              />
            )}

            {currentTab === 'blog' && (
              <BlogView
                posts={posts}
                searchQuery={searchQuery}
                setSearchQuery={setSearchQuery}
                onReadArticle={handleReadArticle}
              />
            )}

            {currentTab === 'reviews' && (
              <ReviewsView
                posts={posts}
                onReadArticle={handleReadArticle}
                onIncrementClicks={handleIncrementClicks}
              />
            )}

            {currentTab === 'about' && (
              <AboutView
                onNavigateTab={(tab) => {
                  setCurrentTab(tab);
                  window.scrollTo({ top: 0, behavior: 'smooth' });
                }}
              />
            )}

            {currentTab === 'contact' && (
              <ContactView />
            )}

            {currentTab === 'ai-wizard' && (
              <AIWizard
                onAddCustomPost={handleAddCustomPost}
                onIncrementClicks={handleIncrementClicks}
                totalEarnings={telemetry.totalCommission}
              />
            )}

            {currentTab === 'telemetry' && (
              <TelemetryHub
                stats={telemetry}
                onIncrementStats={handleIncrementClicks}
                onResetStats={handleResetTelemetryMetric}
              />
            )}
          </>
        )}
      </main>

      {/* 3. Footer Integration */}
      <Footer
        onSubscribe={handleSubscribeNewsletter}
        setCurrentTab={(tab) => {
          setCurrentTab(tab);
          setActiveArticleId(null);
          window.scrollTo({ top: 0, behavior: 'smooth' });
        }}
        onReadArticle={handleReadArticle}
      />

    </div>
  );
}
